package com.smartschool.tests;

import org.testng.Assert;
import org.testng.annotations.*;
import com.smartschool.base.AndroidBase;
import com.smartschool.pages.FeePaymentPage;

public class AndroidFeePaymentTests extends AndroidBase {

    FeePaymentPage feePaymentPage;

    @BeforeClass
    public void setUpPage() {
        feePaymentPage = new FeePaymentPage(driver);
    }

    @Test(priority = 1, description = "TC01 - Fee Payment page navigation")
    public void tc01_feePaymentNavigation() {
        feePaymentPage.clickFeePaymentCard();

        Assert.assertTrue(
            feePaymentPage.isFeePaymentPageDisplayed(),
            "Fee Payment page should be displayed"
        );

        // ✅ Admin data இருந்தாலும் இல்லன்னாலும் — page load ஆச்சுன்னா pass
        Assert.assertTrue(
            feePaymentPage.isFeeDetailsDisplayed(),
            "Fee details or no-invoice message should be displayed"
        );

        System.out.println("TC01 PASSED - Fee Payment page verified");
    }

    @Test(priority = 2, description = "TC02 - Make Payment button")
    public void tc02_makePaymentButton() {
        feePaymentPage.clickFeePaymentCard();

        Assert.assertTrue(
            feePaymentPage.isFeePaymentPageDisplayed(),
            "Fee Payment page should be displayed"
        );

        if (feePaymentPage.isNoInvoiceScenario()) {
            System.out.println("TC02 SKIPPED - No fees generated by admin");
            return;
        }

        Assert.assertTrue(
            feePaymentPage.isMakePaymentButtonDisplayed(),
            "Make Payment button should be displayed"
        );
        System.out.println("TC02 PASSED - Make Payment button verified");
    }

    @AfterClass
    public void goBackToHome() {
        goBack();
    }
}